"""3.10.1

Revision ID: 1f125fdacf28
Revises: fea770db9b1c
Create Date: 2025-11-28 14:25:56.999328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f125fdacf28'
down_revision = 'fea770db9b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('name_unique', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('dish_kitchen_id', sa.Integer(), nullable=False, comment='类别'),
    sa.Column('name_display', sa.String(length=255), nullable=True, comment='显示名称'),
    sa.Column('name_english', sa.String(length=255), nullable=True, comment='英文名称'),
    sa.Column('spec', sa.String(length=255), nullable=True, comment='规格'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='价格'),
    sa.Column('time_on', sa.DateTime(), nullable=True, comment='上架时间'),
    sa.Column('time_off', sa.DateTime(), nullable=True, comment='下架时间'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), nullable=False, comment='0:草稿;2:已发布;9:已下线'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='简介'),
    sa.Column('description_english', sa.String(length=255), nullable=True, comment='英文简介'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique'),
    comment='菜品表'
    )
    op.create_table('dish_bom',
    sa.Column('product_type', sa.Integer(), nullable=False, comment='类型 1/单品;2/套餐'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品'),
    sa.Column('material_type', sa.Integer(), nullable=False, comment='类型 1/食材;2/耗材'),
    sa.Column('material_id', sa.Integer(), nullable=False, comment='物料'),
    sa.Column('spec', sa.String(length=255), nullable=True, comment='规格'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜品BOM表'
    )
    op.create_table('dish_branch',
    sa.Column('dish_id', sa.Integer(), nullable=False, comment='菜品'),
    sa.Column('branch_id', sa.Integer(), nullable=False, comment='店铺'),
    sa.Column('name_display', sa.String(length=255), nullable=True, comment='显示名称'),
    sa.Column('name_english', sa.String(length=255), nullable=True, comment='英文名称'),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='价格'),
    sa.Column('cost_price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='成本价'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), nullable=False, comment='0:草稿;1:已上传;2:已发布;3:库存不足;9:已下线'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='简介'),
    sa.Column('description_english', sa.String(length=255), nullable=True, comment='英文简介'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜品店铺表'
    )
    op.create_table('dish_combo',
    sa.Column('name_unique', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('name_display', sa.String(length=255), nullable=True, comment='显示名称'),
    sa.Column('name_english', sa.String(length=255), nullable=True, comment='英文名称'),
    sa.Column('dish_combo_series_id', sa.Integer(), nullable=False, comment='菜品套餐系列'),
    sa.Column('person_number', sa.Integer(), nullable=False, comment='人数'),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='价格'),
    sa.Column('cost_price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='成本价'),
    sa.Column('time_on', sa.DateTime(), nullable=True, comment='上架时间'),
    sa.Column('time_off', sa.DateTime(), nullable=True, comment='下架时间'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('status', sa.Integer(), nullable=False, comment='0:草稿;1:已上传;2:已发布;9:已下线'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='简介'),
    sa.Column('description_english', sa.String(length=255), nullable=True, comment='英文简介'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique'),
    comment='菜品套餐表'
    )
    op.create_table('dish_combo_detail',
    sa.Column('dish_combo_id', sa.Integer(), nullable=False, comment='菜品套餐'),
    sa.Column('dish_group_id', sa.Integer(), nullable=False, comment='菜品组'),
    sa.Column('name_display', sa.String(length=255), nullable=True, comment='显示名称'),
    sa.Column('name_english', sa.String(length=255), nullable=True, comment='英文名称'),
    sa.Column('choose_number', sa.Integer(), nullable=False, comment='可选数量'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜品套餐详情表'
    )
    op.create_table('dish_combo_series',
    sa.Column('name_unique', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique'),
    comment='菜品套餐系列表'
    )
    op.create_table('dish_group',
    sa.Column('name_unique', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('name_display', sa.String(length=255), nullable=True, comment='显示名称'),
    sa.Column('name_english', sa.String(length=255), nullable=True, comment='英文名称'),
    sa.Column('dish_group_type_id', sa.Integer(), nullable=False, comment='菜品组类型'),
    sa.Column('stype', sa.Integer(), nullable=False, comment='类型 0/可选;2/必选'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique'),
    comment='菜品组表'
    )
    op.create_table('dish_group_detail',
    sa.Column('dish_group_id', sa.Integer(), nullable=False, comment='菜品组'),
    sa.Column('dish_id', sa.Integer(), nullable=False, comment='菜品'),
    sa.Column('additional_price', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='加价'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜品组详情表'
    )
    op.create_table('dish_group_type',
    sa.Column('name_unique', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique'),
    comment='菜品组类型表'
    )
    op.create_table('dish_image',
    sa.Column('product_type', sa.Integer(), nullable=False, comment='类型 1/单品;2/套餐'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品'),
    sa.Column('img_platform', sa.String(length=50), nullable=False, comment='图片平台'),
    sa.Column('img_url', sa.String(length=255), nullable=False, comment='图片地址'),
    sa.Column('is_first', sa.Boolean(), nullable=False, comment='是否首图'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='产品图片表'
    )
    op.create_table('dish_kitchen',
    sa.Column('name_unique', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique'),
    comment='厨部表'
    )
    op.create_table('dish_kitchen_branch',
    sa.Column('branch_id', sa.Integer(), nullable=False, comment='店铺'),
    sa.Column('dish_kitchen_id', sa.Integer(), nullable=False, comment='厨部'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='厨部店铺表'
    )
    op.create_table('dish_tag',
    sa.Column('name_unique', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique'),
    comment='标签表'
    )
    op.create_table('dish_tagging',
    sa.Column('dish_id', sa.Integer(), nullable=False, comment='菜品'),
    sa.Column('dish_tag_id', sa.Integer(), nullable=False, comment='标签'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜品标签表'
    )
    op.alter_column('branch', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('branch', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('company', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('company', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_dept', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_dept', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_menu', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_menu', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_role', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_role', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_user', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_user', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_operation', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_operation', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_sms_send', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_sms_send', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_details', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_details', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_type', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_type', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_settings', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_settings', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_settings_tab', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_settings_tab', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vadmin_system_settings_tab', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_settings_tab', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_settings', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_settings', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_type', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_type', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_details', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_system_dict_details', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_sms_send', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_sms_send', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_operation', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_record_operation', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_user', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_user', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_role', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_role', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_menu', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_menu', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_dept', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('vadmin_auth_dept', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('company', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('company', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('branch', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('branch', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_table('dish_tagging')
    op.drop_table('dish_tag')
    op.drop_table('dish_kitchen_branch')
    op.drop_table('dish_kitchen')
    op.drop_table('dish_image')
    op.drop_table('dish_group_type')
    op.drop_table('dish_group_detail')
    op.drop_table('dish_group')
    op.drop_table('dish_combo_series')
    op.drop_table('dish_combo_detail')
    op.drop_table('dish_combo')
    op.drop_table('dish_branch')
    op.drop_table('dish_bom')
    op.drop_table('dish')
    # ### end Alembic commands ###
