"""add_operation_content_field

Revision ID: add_operation_content
Revises: 2639269f5ab4
Create Date: 2025-11-25 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_operation_content'
down_revision = '2639269f5ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vadmin_record_operation', 
                  sa.Column('operation_content', sa.String(length=50), nullable=True, comment='操作内容'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vadmin_record_operation', 'operation_content')
    # ### end Alembic commands ###

