"""move_log_menus_to_system

Revision ID: move_log_menus
Revises: add_operation_content
Create Date: 2025-11-25 17:00:00.000000

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'move_log_menus'
down_revision = 'add_operation_content'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 将"操作日志"和"调度日志"菜单从"日志管理"转移到"系统管理"
    
    # 首先获取系统管理和日志管理的菜单ID
    connection = op.get_bind()
    
    # 获取系统管理菜单ID
    system_menu = connection.execute(text("SELECT id FROM vadmin_auth_menu WHERE title = '系统管理' AND is_delete = 0")).fetchone()
    if not system_menu:
        raise ValueError("未找到'系统管理'菜单")
    system_menu_id = system_menu[0]
    
    # 获取日志管理菜单ID
    log_menu = connection.execute(text("SELECT id FROM vadmin_auth_menu WHERE title = '日志管理' AND is_delete = 0")).fetchone()
    if not log_menu:
        raise ValueError("未找到'日志管理'菜单")
    log_menu_id = log_menu[0]
    
    # 更新操作日志菜单的parent_id为系统管理
    op.execute(text("""
        UPDATE vadmin_auth_menu 
        SET parent_id = :system_id 
        WHERE title = '操作日志' AND parent_id = :log_id AND is_delete = 0
    """).bindparams(system_id=system_menu_id, log_id=log_menu_id))
    
    # 更新调度日志菜单的parent_id为系统管理（如果存在）
    op.execute(text("""
        UPDATE vadmin_auth_menu 
        SET parent_id = :system_id 
        WHERE title = '调度日志' AND parent_id = :log_id AND is_delete = 0
    """).bindparams(system_id=system_menu_id, log_id=log_menu_id))
    
    # 如果"日志管理"菜单下没有其他子菜单了，可以选择删除它
    # 这里先不删除，保留菜单以便将来可能使用
    # 如果需要删除，可以执行：
    # op.execute(text("UPDATE vadmin_auth_menu SET is_delete = 1 WHERE id = :log_id").bindparams(log_id=log_menu_id))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 将菜单还原到"日志管理"下
    connection = op.get_bind()
    
    # 获取系统管理和日志管理的菜单ID
    system_menu = connection.execute(text("SELECT id FROM vadmin_auth_menu WHERE title = '系统管理' AND is_delete = 0")).fetchone()
    log_menu = connection.execute(text("SELECT id FROM vadmin_auth_menu WHERE title = '日志管理' AND is_delete = 0")).fetchone()
    
    if system_menu and log_menu:
        system_menu_id = system_menu[0]
        log_menu_id = log_menu[0]
        
        # 还原操作日志菜单
        op.execute(text("""
            UPDATE vadmin_auth_menu 
            SET parent_id = :log_id 
            WHERE title = '操作日志' AND parent_id = :system_id AND is_delete = 0
        """).bindparams(log_id=log_menu_id, system_id=system_menu_id))
        
        # 还原调度日志菜单
        op.execute(text("""
            UPDATE vadmin_auth_menu 
            SET parent_id = :log_id 
            WHERE title = '调度日志' AND parent_id = :system_id AND is_delete = 0
        """).bindparams(log_id=log_menu_id, system_id=system_menu_id))
    # ### end Alembic commands ###

